In [6]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [7]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [8]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


![Screenshot (330).png](<attachment:Screenshot (330).png>)

In [9]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [10]:
for i in enumerate(chars):
    print(i) #it will return a tuple

(0, '\n')
(1, ' ')
(2, '!')
(3, '$')
(4, '&')
(5, "'")
(6, ',')
(7, '-')
(8, '.')
(9, '3')
(10, ':')
(11, ';')
(12, '?')
(13, 'A')
(14, 'B')
(15, 'C')
(16, 'D')
(17, 'E')
(18, 'F')
(19, 'G')
(20, 'H')
(21, 'I')
(22, 'J')
(23, 'K')
(24, 'L')
(25, 'M')
(26, 'N')
(27, 'O')
(28, 'P')
(29, 'Q')
(30, 'R')
(31, 'S')
(32, 'T')
(33, 'U')
(34, 'V')
(35, 'W')
(36, 'X')
(37, 'Y')
(38, 'Z')
(39, 'a')
(40, 'b')
(41, 'c')
(42, 'd')
(43, 'e')
(44, 'f')
(45, 'g')
(46, 'h')
(47, 'i')
(48, 'j')
(49, 'k')
(50, 'l')
(51, 'm')
(52, 'n')
(53, 'o')
(54, 'p')
(55, 'q')
(56, 'r')
(57, 's')
(58, 't')
(59, 'u')
(60, 'v')
(61, 'w')
(62, 'x')
(63, 'y')
(64, 'z')


In [11]:
stoi = { i for i in enumerate(chars) }
print(stoi)

{(28, 'P'), (25, 'M'), (30, 'R'), (0, '\n'), (43, 'e'), (45, 'g'), (33, 'U'), (56, 'r'), (14, 'B'), (21, 'I'), (62, 'x'), (19, 'G'), (20, 'H'), (41, 'c'), (27, 'O'), (11, ';'), (55, 'q'), (63, 'y'), (32, 'T'), (5, "'"), (40, 'b'), (61, 'w'), (48, 'j'), (17, 'E'), (60, 'v'), (24, 'L'), (64, 'z'), (29, 'Q'), (39, 'a'), (52, 'n'), (36, 'X'), (49, 'k'), (42, 'd'), (7, '-'), (6, ','), (13, 'A'), (57, 's'), (1, ' '), (26, 'N'), (38, 'Z'), (23, 'K'), (15, 'C'), (35, 'W'), (53, 'o'), (46, 'h'), (51, 'm'), (9, '3'), (50, 'l'), (34, 'V'), (59, 'u'), (10, ':'), (54, 'p'), (18, 'F'), (47, 'i'), (31, 'S'), (44, 'f'), (12, '?'), (8, '.'), (4, '&'), (37, 'Y'), (2, '!'), (22, 'J'), (58, 't'), (16, 'D'), (3, '$')}


In [12]:
stoi = { ch:i for i,ch in enumerate(chars) }
print(stoi)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [13]:
itos = { i:ch for i,ch in enumerate(chars) }
print(itos)

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'}


**"lambda" functions are anonymous functions. They are useful when you need a small function temporarily and don't want to define a full function with def.** `lambda parameters: expression`

In [14]:
square = lambda x: x ** 2
print(square(5)) 

25


In [15]:
def square(x):
    return x ** 2

In [16]:
encode = lambda s: [stoi[c] for c in s] #list comprehension
a = encode("abc")
print(a)

[39, 40, 41]


In [17]:
s = 'abc'
def encode(s): 
    a = [] 
    for c in s:  
        a.append(stoi[c])
    return a
data = encode(s)
print(data)


[39, 40, 41]


**PyTorch tensor is a multi-dimensional array or matrix that is used to store data and perform computations in PyTorch**

In [18]:
import torch

c:\Users\karthee\Desktop\CSULB\Project\LLM Project\llmvenv\Lib\site-packages\torch\_subclasses\functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [19]:
random_tensor = torch.randn(3, 3)  # 3x3 tensor with random values from normal distribution
print(random_tensor)

tensor([[ 4.4681e-01, -1.2937e-01, -3.8864e-01],
        [ 7.2117e-01, -1.1362e+00, -4.3022e-01],
        [-3.9224e-01,  3.6845e-04,  3.9896e-01]])


In [20]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:] 

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [21]:
batch_size =32 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200 

In [23]:
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

In [24]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [25]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [26]:
xb, yb = get_batch('train') #comment
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

inputs:
torch.Size([32, 8])
tensor([[ 0, 31, 43, 41, 53, 52, 42,  1],
        [53, 42,  1, 61, 47, 50, 50,  1],
        [40, 50, 53, 53, 42,  1, 57, 46],
        [27, 10,  0, 15, 53, 51, 43,  1],
        [43,  1, 41, 53, 51, 54, 39, 52],
        [43,  0, 32, 46, 39, 58,  1, 63],
        [ 1, 57, 59, 56, 60, 43, 63,  1],
        [52, 47, 45, 46, 58,  8,  0, 19],
        [26, 17, 10,  0, 32, 46, 39, 58],
        [ 1, 57, 61, 53, 56, 42,  6,  0],
        [57, 11,  0, 24, 43, 58,  1, 52],
        [54, 56, 53, 59, 42,  1, 14, 53],
        [58, 46, 43, 56, 46, 53, 53, 42],
        [39,  1, 61, 53, 51, 39, 52,  1],
        [47, 60, 43,  1, 42, 47, 56, 43],
        [57, 43, 10,  0, 25, 39, 56, 56],
        [42,  1, 46, 47, 57,  1, 46, 47],
        [31, 32, 17, 30, 10,  0, 15, 59],
        [58, 46, 43,  1, 57, 39, 51, 43],
        [47, 57,  1, 58, 56, 47, 42, 43],
        [35, 46, 39, 58,  1, 51, 59, 57],
        [50, 43,  1, 58, 46, 47, 52, 49],
        [17, 24, 21, 38, 13, 14, 17, 32],
      