In [35]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [36]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [37]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


![Screenshot (330).png](<attachment:Screenshot (330).png>)

In [38]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [39]:
for i in enumerate(chars):
    print(i) #it will return a tuple

(0, '\n')
(1, ' ')
(2, '!')
(3, '$')
(4, '&')
(5, "'")
(6, ',')
(7, '-')
(8, '.')
(9, '3')
(10, ':')
(11, ';')
(12, '?')
(13, 'A')
(14, 'B')
(15, 'C')
(16, 'D')
(17, 'E')
(18, 'F')
(19, 'G')
(20, 'H')
(21, 'I')
(22, 'J')
(23, 'K')
(24, 'L')
(25, 'M')
(26, 'N')
(27, 'O')
(28, 'P')
(29, 'Q')
(30, 'R')
(31, 'S')
(32, 'T')
(33, 'U')
(34, 'V')
(35, 'W')
(36, 'X')
(37, 'Y')
(38, 'Z')
(39, 'a')
(40, 'b')
(41, 'c')
(42, 'd')
(43, 'e')
(44, 'f')
(45, 'g')
(46, 'h')
(47, 'i')
(48, 'j')
(49, 'k')
(50, 'l')
(51, 'm')
(52, 'n')
(53, 'o')
(54, 'p')
(55, 'q')
(56, 'r')
(57, 's')
(58, 't')
(59, 'u')
(60, 'v')
(61, 'w')
(62, 'x')
(63, 'y')
(64, 'z')


In [40]:
stoi = { i for i in enumerate(chars) }
print(stoi)

{(21, 'I'), (28, 'P'), (50, 'l'), (8, '.'), (51, 'm'), (5, "'"), (20, 'H'), (42, 'd'), (62, 'x'), (44, 'f'), (30, 'R'), (35, 'W'), (7, '-'), (29, 'Q'), (27, 'O'), (59, 'u'), (3, '$'), (34, 'V'), (12, '?'), (1, ' '), (46, 'h'), (58, 't'), (18, 'F'), (48, 'j'), (15, 'C'), (13, 'A'), (22, 'J'), (10, ':'), (57, 's'), (2, '!'), (61, 'w'), (41, 'c'), (63, 'y'), (24, 'L'), (53, 'o'), (56, 'r'), (36, 'X'), (43, 'e'), (47, 'i'), (39, 'a'), (16, 'D'), (52, 'n'), (25, 'M'), (23, 'K'), (32, 'T'), (37, 'Y'), (49, 'k'), (40, 'b'), (11, ';'), (14, 'B'), (60, 'v'), (17, 'E'), (38, 'Z'), (4, '&'), (19, 'G'), (31, 'S'), (54, 'p'), (64, 'z'), (0, '\n'), (6, ','), (26, 'N'), (45, 'g'), (9, '3'), (55, 'q'), (33, 'U')}


In [41]:
stoi = { ch:i for i,ch in enumerate(chars) }
print(stoi)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [42]:
itos = { i:ch for i,ch in enumerate(chars) }
print(itos)

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'}


**"lambda" functions are anonymous functions. They are useful when you need a small function temporarily and don't want to define a full function with def.** `lambda parameters: expression`

In [43]:
square = lambda x: x ** 2
print(square(5)) 

25


In [44]:
def square(x):
    return x ** 2

In [45]:
encode = lambda s: [stoi[c] for c in s] #list comprehension
a = encode("abc")
print(a)

[39, 40, 41]


In [46]:
s = 'abc'
def encode(s): 
    a = [] 
    for c in s:  
        a.append(stoi[c])
    return a
data = encode(s)
print(data)


[39, 40, 41]


**PyTorch tensor is a multi-dimensional array or matrix that is used to store data and perform computations in PyTorch**

In [47]:
import torch

In [48]:
random_tensor = torch.randn(3, 3)  # 3x3 tensor with random values from normal distribution
print(random_tensor)

tensor([[ 1.0130,  0.4786, -1.5338],
        [-0.5835,  1.9606, -2.1773],
        [-1.2816, -1.5758, -0.3407]])


In [49]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:] 

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [50]:
batch_size =32 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200 

In [51]:
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

In [52]:
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [53]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([18]) the target: 47
when input is tensor([18, 47]) the target: 56
when input is tensor([18, 47, 56]) the target: 57
when input is tensor([18, 47, 56, 57]) the target: 58
when input is tensor([18, 47, 56, 57, 58]) the target: 1
when input is tensor([18, 47, 56, 57, 58,  1]) the target: 15
when input is tensor([18, 47, 56, 57, 58,  1, 15]) the target: 47
when input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) the target: 58


In [54]:
xb, yb = get_batch('train') #comment
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

inputs:
torch.Size([32, 8])
tensor([[42, 56, 39, 47, 52,  0, 32, 46],
        [56, 51, 43, 56,  1, 51, 39, 50],
        [17, 31, 32, 25, 27, 30, 17, 24],
        [26, 16, 10,  0, 32, 46, 43,  1],
        [ 0, 32, 46, 43,  1, 54, 59, 56],
        [42,  1, 41, 46, 53, 49, 43,  1],
        [17, 26, 32, 21, 27, 10,  0, 31],
        [51, 63,  1, 57, 39, 63, 47, 52],
        [59,  1, 44, 39, 50, 50,  1, 59],
        [56,  1, 43, 56, 43,  1, 63, 53],
        [43,  1, 43, 60, 43, 56, 63,  1],
        [ 1, 57, 43, 52, 42, 47, 52, 45],
        [ 1, 57, 43, 56, 60, 39, 52, 58],
        [46, 53, 59,  1, 41, 39, 52, 57],
        [50, 58,  1, 40, 43,  1, 53, 52],
        [46,  1, 40, 63,  1, 51, 63,  1],
        [56, 43, 57, 53, 50, 60, 43, 42],
        [ 1, 42, 47, 42,  0, 30, 59, 52],
        [58, 58, 43, 56,  1, 57, 43, 52],
        [42, 43, 56,  6,  1, 63, 53, 59],
        [50,  1, 39, 57,  1, 50, 53, 52],
        [50, 53, 61, 43, 56, 57,  1, 58],
        [39, 56,  6,  1, 61, 46, 53,  1],
      

In [55]:
words = ['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [56]:
for w in words[:1]:
  for ch1, ch2 in zip(w, w[1:]):
    print(ch1, ch2)

e m
m m
m a


`dictionary.get(keyname, value)` where keyname is The keyname of the item you want to return the value from and value is A value to return if the specified key does not exist

In [57]:
b = {}
bigram = ('h', 'e')

# First encounter of ('h', 'e')
count = b.get(bigram, 0)  # Since ('h', 'e') is not in b, this returns 0
b[bigram] = count + 1     # Sets b[('h', 'e')] to 1
print(b)

{('h', 'e'): 1}


In [58]:

b = {}
for w in words:
  chs = ['<S>'] + list(w) + ['<E>']
  for ch1, ch2 in zip(chs, chs[1:]):
    bigram = (ch1, ch2)
    b[bigram] = b.get(bigram, 0) + 1

In [59]:
sorted(b.items(), key = lambda kv: -kv[1])

[(('a', '<E>'), 7),
 (('i', 'a'), 4),
 (('e', 'l'), 3),
 (('<S>', 'e'), 2),
 (('l', 'i'), 2),
 (('<S>', 'a'), 2),
 (('h', 'a'), 2),
 (('a', 'r'), 2),
 (('e', 'm'), 1),
 (('m', 'm'), 1),
 (('m', 'a'), 1),
 (('<S>', 'o'), 1),
 (('o', 'l'), 1),
 (('i', 'v'), 1),
 (('v', 'i'), 1),
 (('a', 'v'), 1),
 (('v', 'a'), 1),
 (('<S>', 'i'), 1),
 (('i', 's'), 1),
 (('s', 'a'), 1),
 (('a', 'b'), 1),
 (('b', 'e'), 1),
 (('l', 'l'), 1),
 (('l', 'a'), 1),
 (('<S>', 's'), 1),
 (('s', 'o'), 1),
 (('o', 'p'), 1),
 (('p', 'h'), 1),
 (('h', 'i'), 1),
 (('<S>', 'c'), 1),
 (('c', 'h'), 1),
 (('r', 'l'), 1),
 (('l', 'o'), 1),
 (('o', 't'), 1),
 (('t', 't'), 1),
 (('t', 'e'), 1),
 (('e', '<E>'), 1),
 (('<S>', 'm'), 1),
 (('m', 'i'), 1),
 (('a', 'm'), 1),
 (('m', 'e'), 1),
 (('<S>', 'h'), 1),
 (('r', 'p'), 1),
 (('p', 'e'), 1),
 (('e', 'r'), 1),
 (('r', '<E>'), 1),
 (('e', 'v'), 1),
 (('v', 'e'), 1),
 (('l', 'y'), 1),
 (('y', 'n'), 1),
 (('n', '<E>'), 1)]

In [60]:
x = {
  ('h', 'e'): 2,
  ('e', 'l'): 1,
  ('l', 'l'): 1,
  ('l', 'o'): 1,
  ('o', '<E>'): 1
}

In [61]:
sorted(x.items(), key = lambda kv: -kv[1])

[(('h', 'e'), 2),
 (('e', 'l'), 1),
 (('l', 'l'), 1),
 (('l', 'o'), 1),
 (('o', '<E>'), 1)]

In [62]:
vocab = ["I", "like", "cats", "dogs", "car", "shwetha"]
vocab_size = len(vocab)

In [63]:
import torch
import torch.nn as nn

# Define the vocabulary size and the input tensor
vocab_size = len(vocab) # for example, a vocabulary size of 10
B, T = 2, 5  # Batch size (B) and sequence length (T)

# Initialize the embedding layer (equivalent to self.token_embedding_table)
token_embedding_table = nn.Embedding(vocab_size, vocab_size)

# Define an example input tensor idx of shape (B, T)
idx = torch.randint(0, vocab_size, (B, T))  # Random integer values in the range [0, vocab_size)
print("Input idx:\n", idx)

# Forward pass
logits = token_embedding_table(idx)  # Output shape will be (B, T, C) where C = vocab_size
print("\nLogits:\n", logits)

Input idx:
 tensor([[4, 4, 0, 1, 3],
        [4, 2, 0, 5, 4]])

Logits:
 tensor([[[ 1.3940, -0.5681, -0.5765, -0.0823,  0.9343, -0.6740],
         [ 1.3940, -0.5681, -0.5765, -0.0823,  0.9343, -0.6740],
         [-0.8982, -0.1593, -0.1351, -1.8574, -1.2355,  0.3585],
         [-1.4117, -0.0254, -0.2865, -0.0451,  0.2312, -0.9341],
         [ 1.0827, -0.9749, -0.1530,  0.1494,  0.7607,  0.7706]],

        [[ 1.3940, -0.5681, -0.5765, -0.0823,  0.9343, -0.6740],
         [ 0.1232, -0.8815, -0.0243,  0.6466, -1.0736, -1.4312],
         [-0.8982, -0.1593, -0.1351, -1.8574, -1.2355,  0.3585],
         [-0.2351,  0.6542, -3.1659,  0.2164,  1.2839,  1.4845],
         [ 1.3940, -0.5681, -0.5765, -0.0823,  0.9343, -0.6740]]],
       grad_fn=<EmbeddingBackward0>)


In [64]:
import torch
import torch.nn.functional as F
import torch.nn as nn

# Example parameters
B, T, vocab_size = 2, 3, 5  # batch size, sequence length, vocabulary size

# Initialize embedding layer manually (usually in __init__ in a class)
token_embedding_table = nn.Embedding(vocab_size, vocab_size)

# Example input tensors
idx = torch.tensor([[0, 1, 2], [2, 3, 4]])  # (B, T)
targets = torch.tensor([[1, 2, 3], [3, 4, 0]])  # (B, T)

# Step 1: Look up logits from the embedding table
logits = token_embedding_table(idx)  # Shape will be (B, T, C)
print("Logits after embedding lookup:", logits)
print("Logits shape:", logits.shape)  # Expected shape: (B, T, vocab_size)

# Step 2: Check if targets are provided to calculate loss
if targets is None:
    loss = None
else:
    # Step 3: Get shapes of B, T, and C from logits
    B, T, C = logits.shape
    print("B, T, C:", B, T, C)

    # Step 4: Flatten logits and targets for cross-entropy computation
    logits = logits.view(B * T, C)
    print("Logits after reshaping:", logits)
    print("Logits shape after reshaping:", logits.shape)  # Expected shape: (B*T, C)

    targets = targets.view(B * T)
    print("Targets after reshaping:", targets)
    print("Targets shape after reshaping:", targets.shape)  # Expected shape: (B*T,)

    # Step 5: Calculate the cross-entropy loss
    loss = F.cross_entropy(logits, targets)
    print("Cross-entropy loss:", loss)

Logits after embedding lookup: tensor([[[-0.5698, -0.3917, -2.5088, -0.2929, -0.4578],
         [-1.7342,  0.2785, -0.7114,  1.6899,  0.5533],
         [-0.7548,  0.2590,  1.8964, -0.0588,  0.2411]],

        [[-0.7548,  0.2590,  1.8964, -0.0588,  0.2411],
         [-0.9542, -0.0894, -1.8531, -0.1106, -0.7076],
         [ 0.0239, -1.0283, -0.2174,  1.8099,  1.5296]]],
       grad_fn=<EmbeddingBackward0>)
Logits shape: torch.Size([2, 3, 5])
B, T, C: 2 3 5
Logits after reshaping: tensor([[-0.5698, -0.3917, -2.5088, -0.2929, -0.4578],
        [-1.7342,  0.2785, -0.7114,  1.6899,  0.5533],
        [-0.7548,  0.2590,  1.8964, -0.0588,  0.2411],
        [-0.7548,  0.2590,  1.8964, -0.0588,  0.2411],
        [-0.9542, -0.0894, -1.8531, -0.1106, -0.7076],
        [ 0.0239, -1.0283, -0.2174,  1.8099,  1.5296]],
       grad_fn=<ViewBackward0>)
Logits shape after reshaping: torch.Size([6, 5])
Targets after reshaping: tensor([1, 2, 3, 3, 4, 0])
Targets shape after reshaping: torch.Size([6])
Cross-

`generate` method

In [65]:
import torch
import torch.nn.functional as F

# Define the vocabulary size and initialize the model
vocab_size = 3 # Example vocabulary size
B, T = 2, 3  # Batch size and sequence length for demonstration
max_new_tokens = 5  # Number of new tokens to generate

# Starting sequence, a (B, T) tensor of indices
idx = torch.randint(0, vocab_size, (B, T))  # Initial random tokens
#print("Initial idx:", idx)  # Shape: (B, T)

# Simulate the model's token embedding table (simplified for this example)
token_embedding_table = torch.nn.Embedding(vocab_size, vocab_size)
#print("Token Embedding Table:", token_embedding_table.weight)

# Run the generation loop for a specified number of new tokens
for _ in range(max_new_tokens):
    # Get the predictions by looking up embeddings (simulates the forward pass of the model)
    logits = token_embedding_table(idx)  # Shape: (B, T, vocab_size)
    #print("\nLogits (output of token embedding):", logits)

    # Focus only on the last time step
    logits = logits[:, -1, :]  # Shape: (B, vocab_size)
    #print("Logits at the last time step:", logits)

    # Apply softmax to get probabilities
    probs = F.softmax(logits, dim=-1)  # Shape: (B, vocab_size)
    #print("Probabilities after softmax - Dimension = -1:", probs)

    # Sample from the distribution
    idx_next = torch.multinomial(probs, num_samples=1)  # Shape: (B, 1)
    #print("Sampled next token indices:", idx_next)

    # Append sampled index to the running sequence
    idx = torch.cat((idx, idx_next), dim=1)  # Shape: (B, T+1)
    #print("Updated idx with new token:", idx)

#print("\nFinal generated sequence:", idx)
print("Probabilities after softmax - Dimension = -1:", probs)

Probabilities after softmax - Dimension = -1: tensor([[0.2117, 0.6345, 0.1538],
        [0.2117, 0.6345, 0.1538]], grad_fn=<SoftmaxBackward0>)


`logits_last_token = logits[:, -1, :]`

In [66]:
import torch

# Let's assume we have logits of shape (B, T, C)
B, T, C = 3, 5, 5  # 3 sequences, each of length 5, with 10 classes (vocab size)

# Random logits for demonstration
logits = torch.randn(B, T, C)
print("Original logits shape:", logits.shape)
print("Original logits:", logits)

# Now apply the slicing to focus on the last time step of each sequence
logits_last_token = logits[:, -1, :]  # Take the last token (T = 5, last one is T=-1)

print("\nLogits after selecting the last token of each sequence:")
print("Shape of logits_last_token:", logits_last_token.shape)
print(logits_last_token)

Original logits shape: torch.Size([3, 5, 5])
Original logits: tensor([[[ 0.7197, -0.0312,  0.3210, -0.5477, -0.4302],
         [ 0.7591, -1.2154, -0.3034, -0.4355,  0.2557],
         [-1.6738,  1.3958,  0.4602,  1.1874, -0.6585],
         [-0.2604,  0.6578, -0.6115,  0.8724, -0.7121],
         [ 0.7083, -0.5542,  0.8778,  0.0765,  0.4233]],

        [[-0.0604,  1.3901,  0.5978, -0.8579,  0.5132],
         [ 0.3595,  1.1219,  0.0804,  0.3566,  0.1255],
         [ 0.3984, -0.8485, -0.5143,  0.7305, -0.1207],
         [ 1.2420,  0.9079,  0.3548,  0.7696, -0.1712],
         [-0.4675, -0.8515,  0.0537,  0.7609, -0.6885]],

        [[-1.7235,  0.6089,  1.2678,  1.1129,  0.3321],
         [-1.3550, -1.3064,  0.0601, -1.8122,  0.6211],
         [ 0.4274,  0.1511,  0.9602, -0.5113, -0.4914],
         [-0.2934,  0.0562,  0.3438, -1.1166,  0.9537],
         [-0.5646, -0.0401, -0.7710,  2.2142, -0.7124]]])

Logits after selecting the last token of each sequence:
Shape of logits_last_token: torch.S

In [67]:
import torch

# Sample probabilities for 3 sequences (batch size = 3) with 5 possible tokens (vocabulary size = 5)
probs = torch.tensor([[0.1, 0.3, 0.4, 0.1, 0.1],    # probabilities for sequence 1
                      [0.2, 0.1, 0.1, 0.3, 0.3],    # probabilities for sequence 2
                      [0.3, 0.2, 0.2, 0.1, 0.2]])   # probabilities for sequence 3

# Sample the next token (1 token for each sequence)
idx_next = torch.multinomial(probs, num_samples=1)

print("Next token indices sampled for each sequence:", idx_next)

Next token indices sampled for each sequence: tensor([[2],
        [0],
        [0]])


In [69]:
from transformers import GPT2TokenizerFast

# Use GPT2TokenizerFast directly for compatibility
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
text = "Tokenization is fun!"
tokens = tokenizer.tokenize(text)
print(tokens)

['Token', 'ization', 'Ġis', 'Ġfun', '!']


**Byte-Pair Encoding**

In [ ]:
text = "I love you shwetha. I miss you so much"

chars = sorted(set(text))  # Unique characters in the text
stoi = {ch: i for i, ch in enumerate(chars)}  # String to integer
itos = {i: ch for i, ch in enumerate(chars)}  # Integer to string

# GPT-2 Tokenizer (subword-level encoding)
from transformers import GPT2TokenizerFast

# Use GPT2TokenizerFast directly for compatibility
tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
tokens = tokenizer.tokenize(text)
encoded_tokens = tokenizer.encode(text)
decoded_text = tokenizer.decode(encoded_tokens)

print("Subword tokens:", tokens)
print("Subword encoded:", encoded_tokens)
print("Subword decoded:", decoded_text)