In [1]:
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  1115394


In [3]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
65


![Screenshot (330).png](<attachment:Screenshot (330).png>)

In [56]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("hii there"))
print(decode(encode("hii there")))

[46, 47, 47, 1, 58, 46, 43, 56, 43]
hii there


In [ ]:
for i in enumerate(chars):
    print(i) #it will return a tuple

In [12]:
stoi = { i for i in enumerate(chars) }
print(stoi)

{(49, 'k'), (61, 'w'), (40, 'b'), (60, 'v'), (19, 'G'), (48, 'j'), (4, '&'), (35, 'W'), (8, '.'), (10, ':'), (31, 'S'), (20, 'H'), (6, ','), (14, 'B'), (22, 'J'), (7, '-'), (52, 'n'), (42, 'd'), (56, 'r'), (43, 'e'), (55, 'q'), (59, 'u'), (16, 'D'), (51, 'm'), (24, 'L'), (1, ' '), (5, "'"), (34, 'V'), (57, 's'), (47, 'i'), (50, 'l'), (15, 'C'), (23, 'K'), (32, 'T'), (53, 'o'), (64, 'z'), (58, 't'), (33, 'U'), (25, 'M'), (28, 'P'), (0, '\n'), (11, ';'), (2, '!'), (29, 'Q'), (18, 'F'), (26, 'N'), (9, '3'), (13, 'A'), (21, 'I'), (27, 'O'), (45, 'g'), (36, 'X'), (37, 'Y'), (30, 'R'), (3, '$'), (62, 'x'), (12, '?'), (44, 'f'), (39, 'a'), (41, 'c'), (46, 'h'), (63, 'y'), (54, 'p'), (17, 'E'), (38, 'Z')}


In [14]:
stoi = { ch:i for i,ch in enumerate(chars) }
print(stoi)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [10]:
itos = { i:ch for i,ch in enumerate(chars) }
print(itos)

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'}


**"lambda" functions are anonymous functions. They are useful when you need a small function temporarily and don't want to define a full function with def.** `lambda parameters: expression`

In [15]:
square = lambda x: x ** 2
print(square(5)) 

25


In [ ]:
def square(x):
    return x ** 2

In [ ]:
encode = lambda s: [stoi[c] for c in s] #list comprehension
a = encode("abc")
print(a)

[39, 40, 41]


In [ ]:
s = 'abc'
def encode(s): 
    a = [] 
    for c in s:  
        a.append(stoi[c])
    return a
data = encode(s)
print(data)


[39, 40, 41]


**PyTorch tensor is a multi-dimensional array or matrix that is used to store data and perform computations in PyTorch**

In [ ]:
import torch

In [61]:
random_tensor = torch.randn(3, 3)  # 3x3 tensor with random values from normal distribution
print(random_tensor)

tensor([[-0.2376, -1.3743, -0.2396],
        [ 0.6130, -0.0225, -0.9432],
        [ 1.2946,  2.0293,  0.7938]])


In [ ]:
data = torch.tensor(encode(text), dtype=torch.long)
print(data[:100])
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:] 

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])


In [ ]:
batch_size =32 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?
max_iters = 3000
eval_interval = 300
learning_rate = 1e-2
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200 

In [63]:
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

In [ ]:
xb, yb = get_batch('train') #comment
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

inputs:
torch.Size([32, 8])
tensor([[50, 42,  1, 63, 53, 59,  1, 50],
        [56, 51,  1, 58, 46, 43, 43,  8],
        [42,  1, 47, 58,  1, 40, 43,  6],
        [43, 50, 44,  6,  0, 21,  5, 50],
        [58, 46,  1, 51, 53, 56, 43,  1],
        [47, 57, 58, 43, 52,  1, 58, 53],
        [53, 53, 42,  1, 58, 53, 52, 45],
        [56,  5, 57,  1, 59, 52, 41, 50],
        [57, 43,  6,  0, 15, 39, 52,  1],
        [57, 43, 50, 60, 43, 57, 11,  0],
        [46, 53, 61,  1, 39,  1, 59, 57],
        [43, 44, 43, 56,  1, 51, 43,  1],
        [ 1, 50, 47, 44, 43,  8,  0,  0],
        [59,  1, 57, 46, 39, 50, 50,  1],
        [47, 50, 50,  1, 57, 53, 53, 52],
        [ 0, 21, 31, 13, 14, 17, 24, 24],
        [57, 46, 11,  0, 13, 52, 42,  1],
        [52, 45,  1, 59, 54, 53, 52,  1],
        [61, 57,  1, 52, 53, 58,  1, 59],
        [43, 44, 53, 56, 51, 47, 58, 47],
        [39, 56, 54, 43, 47, 39, 52,  1],
        [39, 58, 43, 50, 63, 11,  1, 63],
        [16, 53, 61, 52,  6,  1, 50, 39],
      